STATE = {
    "Fantasy Name": [
        "Aragorn",
        "Legolas",
        "Gimli",
        "Boromir",
        "Frodo",
        "Samwise",
        "Merry",
        "Pippin",
        "Gandalf",
    ],
    "Selected Name": None,
    "Settings": [
        "Castle",
        "Forest",
        "Cave",
        "River",
        "Mountain",
        "Plains",
        "Desert",
        "Ocean",
    ],
    "Selected Setting": None,
    "Plot": [
        "The hero is born with a special destiny.",
        "A dark force threatens the land.",
        "The hero must embark on a journey to save the kingdom.",
        "The hero discovers a powerful artifact that will help them in their quest.",
        "The hero faces a great challenge that tests their courage and strength.",
        "The hero emerges victorious from the challenge.",
        "The hero returns home as a legend.",
        "The hero is celebrated for their bravery and sacrifice.",
        "The hero's story becomes a legend that is told for generations.",
        "The hero's legacy lives on through the generations.",
    ],
    "Selected Plot": None,
}
